name: pyqtnotepad
channels:
  - conda-forge
  - defaults
dependencies:
  # Python版本
  - python>=3.9
  
  # 网络请求
  - requests
  
  # 网页解析
  - beautifulsoup4
  - lxml
  
  # 文档处理（conda可用的包）
  - python-docx
  - python-pptx
  
  # 自动化工具
  - selenium
  
  # 配置文件处理
  - pyyaml
  
  # 进度条
  - tqdm
  
  # 图像处理
  - pillow
  
  # pip安装的依赖（conda中不可用或版本不匹配）
  - pip
  - pip:
    # PyQt6核心组件（通过pip安装更稳定）
    - PyQt6>=6.0.0
    - PyQt6-WebEngine>=6.0.0
    
    # PDF处理
    - PyMuPDF>=1.20.0  # fitz库，用于PDF预览和处理
    - PyPDF2>=2.0.0    # PDF文本提取
    
    # 语音识别
    - pyaudio>=0.2.11  # 音频录制
    - baidu-aip>=4.16.0  # 百度AI平台SDK
    
    # 自动化工具管理器
    - webdriver-manager>=3.8.0
    
    # AI相关
    - openai>=1.0.0
    
    # Markdown渲染
    - markdown>=3.3.0
    
    # 字符编码检测
    - chardet>=4.0.0